"use client";

import { createContext, useContext, useMemo } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { DEFAULT_LOCALE, isLocale, localeDir, localizedPath } from '@/lib/i18n';

export interface Language {
  code: string;
  name: string;
  dir: 'ltr' | 'rtl';
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', dir: 'ltr' },
  { code: 'ar', name: 'العربية', dir: 'rtl' },
  { code: 'de', name: 'Deutsch', dir: 'ltr' },
  { code: 'es', name: 'Español', dir: 'ltr' },
  { code: 'fr', name: 'Français', dir: 'ltr' },
  { code: 'it', name: 'Italiano', dir: 'ltr' },
  { code: 'pt', name: 'Português', dir: 'ltr' },
  { code: 'tr', name: 'Türkçe', dir: 'ltr' },
  { code: 'ru', name: 'Русский', dir: 'ltr' },
  { code: 'zh', name: '中文', dir: 'ltr' },
  { code: 'ja', name: '日本語', dir: 'ltr' },
  { code: 'ko', name: '한국어', dir: 'ltr' },
  { code: 'pl', name: 'Polski', dir: 'ltr' },
  { code: 'sw', name: 'Kiswahili', dir: 'ltr' }
];

export const translations: Record<string, Record<string, string>> = {
  ar: {
    "Home": "الرئيسية",
    "Privacy": "الخصوصية",
    "Terms": "الشروط",
    "Cookies": "الكوكيز",
    "Read next": "اقرأ أيضاً",
    "Work": "أعمالنا",
    "Services": "خدماتنا",
    "About": "من نحن",
    "Insights": "مقالاتنا",
    "Contact": "اتصل بنا",
    "Get a Quote": "احصل على تسعير",
    "Menu": "القائمة",
    "Close": "إغلاق",
    "Scroll": "اسحب للأسفل",
    "Start a project": "ابدأ مشروعاً",
    "Offices": "مكاتبنا",
    "Back to top": "العودة للأعلى",
    "Thirteen crafts. One cycle.": "ثلاثة عشر حرفة. دورة واحدة.",
    "All services": "كل الخدمات",
    "Our Work": "أعمالنا",
    "Let's tell your untold story": "دعنا نروي قصتك غير المروية",
    "Get in touch": "تواصل معنا",
    "Where story meets execution. Predictable budgets. Premium results.": "حيث تلتقي القصة بالتنفيذ. ميزانيات متوقعة. نتائج متميزة.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "تبدأ كل قصة عظيمة بالشريك الإبداعي المناسب، يجمعهما إيمان واحد. كل علامة تجارية وكل مؤسسة وكل ثقافة لديها قصة تستحق أن تروى.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "نختار عملائنا بعناية كما يختاروننا. تبدأ أقوى الأعمال بالطموح المشترك والتعاون الصادق والثقة في تحدي بعضنا البعض عندما تتطلب القصة ذلك.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "لسنا مجرد موردين عاديين ننتظر التعليمات. نصل كشركاء إبداعيين مستعدين للتساؤل والمساهمة وتولي المسؤولية الكاملة.",
    "Loading...": "جاري التحميل...",
    "Failed to load data": "فشل تحميل البيانات",
    "Learn more →": "اقرأ المزيد ←",
    "Film & Video Production": "إنتاج الأفلام والفيديو",
    "Egypt & MENA": "مصر والشرق الأوسط",
    "Production Services in Egypt & MENA": "خدمات الإنتاج في مصر والشرق الأوسط",
    "Film & Advertising Portfolio": "أعمال الأفلام والإعلانات",
    "Frequently asked questions": "أسئلة شائعة",
    "Questions": "أسئلة",
    "Production insights, practical guides and field notes from film, commercials, documentaries and on-ground work in Egypt and MENA.": "رؤى إنتاجية وأدلة عملية وملاحظات ميدانية من الأفلام والإعلانات والوثائقيات والعمل الميداني في مصر والشرق الأوسط.",
    "About Global Untold Story": "عن Global Untold Story",
    "Contact a Production Studio in Egypt": "تواصل مع استوديو إنتاج في مصر",
    "All rights reserved.": "جميع الحقوق محفوظة.",
    "The idea comes first. Everything else follows.": "الفكرة تأتي أولاً. وكل شيء آخر يتبعها.",
    "Egypt — MENA — Worldwide": "مصر — الشرق الأوسط — العالم",
    "Film, advertising, documentary services, content, post-production and marketing across Egypt, UAE and Saudi Arabia. From the region to the world": "خدمات الأفلام والإعلانات والوثائقيات والمحتوى وما بعد الإنتاج والتسويق في مصر والإمارات والسعودية. من المنطقة إلى العالم",
    "Trusted by": "يثق بنا",
    "Our journey with the Titans": "رحلتنا مع العمالقة",
    "clients": "عميل",
    "repeat business": "عمل متكرر",
    "The studio": "الاستوديو",
    "ENTER AT ANY STAGE LEAVE WITH ONE EPIC RESULT": "ادخل في أي مرحلة وغادر بنتيجة أسطورية واحدة",
    "Think & Align": "فكّر وانسجم",
    "Create": "ابتكر",
    "Prepare": "جهّز",
    "Produce": "أنتج",
    "Finish": "أنهِ",
    "Localize & Amplify": "ترجم وضخّم",
    "Grow": "نّمِّ",
    "Scale": "وسّع النطاق",
    "Objectives, audiences, scope, feasibility and success criteria.": "الأهداف والجماهير والنطاق والجدوى ومعايير النجاح.",
    "Concepts, scripts, treatments, formats and creative direction.": "المفاهيم والسيناريوهات والمعالجات والصيغ والإخراج الإبداعي.",
    "Budgets, schedules, crews, casting, locations, permits and technical planning.": "الميزانيات والجداول والطواقم واختيار الممثلين والمواقع والتصاريح والتخطيط الفني.",
    "Film, photography, studio, live and on-ground execution.": "التصوير السينمائي والفوتوغرافي والاستوديو والبث المباشر والتنفيذ الميداني.",
    "Editing, color, sound, motion, CGI, mastering and versioning.": "المونتاج والألوان والصوت والحركة والمؤثرات والماسترينج وإصدار النسخ.",
    "Multi-language delivery, campaign adaptations, distribution and performance support.": "التسليم متعدد اللغات وتعديلات الحملات والتوزيع ودعم الأداء.",
    "Launch, test, optimize and turn finished content into measurable audience and business momentum.": "أطلق واختبر وحسّن وحوّل المحتوى النهائي إلى جمهور وزخم تجاري ملموس.",
    "Expand winning ideas across platforms, formats, markets and languages without losing creative consistency.": "وسّع الأفكار الناجحة عبر المنصات والصيغ والأسواق واللغات دون فقدان الاتساق الإبداعي.",
    "Some stories are greater than time.": "بعض القصص أعظم من الزمن.",
    "THOUSANDS OF YEARS PASS.": "تمر آلاف السنين.",
    "THE STORY REMAINS.": "وتبقى القصة.",
    "Production support for documentaries, factual series and international crews filming Egypt’s history, culture and heritage.": "دعم إنتاجي للوثائقيات والمسلسلات الواقعية والطواقم الدولية التي تصور تاريخ مصر وثقافتها وتراثها.",
    "The complete production cycle": "دورة الإنتاج المتكاملة",
    "The Complete": "القصة الكاملة",
    "Production Cycle": "دورة الإنتاج",
    "Where story meets execution": "حيث تلتقي القصة بالتنفيذ",
    "Predictable budgets": "ميزانيات متوقعة",
    "Premium results": "نتائج متميزة",
    "Full-service film, video and content production studio serving Egypt, MENA and clients worldwide.": "استوديو إنتاج أفلام وفيديو ومحتوى متكامل يخدم مصر والشرق الأوسط وعملاء حول العالم.",
    "Film": "أفلام",
    "Commercials": "إعلانات",
    "Documentaries": "وثائقيات",
    "Corporate": "شركات",
    "Event Coverage": "تغطية الفعاليات",
    "TV & Live": "تلفزيون وبث مباشر",
    "Podcast": "بودكاست",
    "Post-Production": "ما بعد الإنتاج",
    "Motion · CGI · AI": "موشن · مؤثرات · ذكاء اصطناعي",
    "Localization": "توطين",
    "Photography": "تصوير فوتوغرافي",
    "Read": "اقرأ",
    "Featured": "مميز",
    "Back to work": "العودة للأعمال",
    "All projects": "كل المشاريع",
    "The story ends. The impact lives on.": "تنتهي القصة. ويبقى الأثر.",
    "Selected work created to move beyond the brief across platforms, cultures and audiences.": "أعمال مختارة صُنعت لتتجاوز نص المهمة عبر المنصات والثقافات والجماهير.",
    "Commercials, documentaries, corporate films, live events and photography shot in Egypt and across MENA for brands, platforms and institutions that need the full cycle — from the first treatment to the last deliverable.": "إعلانات وأفلام وثائقية وأفلام مؤسسية وفعاليات حية وتصوير فوتوغرافي في مصر وعبر الشرق الأوسط لعلامات ومنصات ومؤسسات تحتاج الدورة كاملة — من المعالجة الأولى حتى آخر تسليم.",
    "The story is yours": "القصة ملكك",
    "Let's bring it to life": "دعنا نمنحها الحياة",
    "One idea and everything it needs": "فكرة واحدة وكل ما تحتاجه",
    "The right strategy, talent, technology and execution assembled around the needs of every project.": "الاستراتيجية والموهبة والتقنية والتنفيذ الصحيح، مجتمعة حول احتياجات كل مشروع.",
    "Under the leadership of CEO Khaled Bendary, our team owns the complete production cycle: strategy and planning, filming, live execution, post-production, delivery and localization. Brands, platforms, broadcasters, institutions and international crews trust us with the stories that matter most to them — and 90% come back for the next one.": "تحت قيادة الرئيس التنفيذي خالد بنداري، يملك فريقنا دورة الإنتاج المتكاملة: الاستراتيجية والتخطيط والتصوير والتنفيذ المباشر وما بعد الإنتاج والتسليم والتوطين. تثق بنا العلامات التجارية والمنصات والقنوات والمؤسسات والطواقم الدولية في أهم القصص لديهم — و90% منهم يعودون للقصة التالية.",
    "Based in Egyptian Media Production City, with offices in Dubai and Jeddah, we run film, advertising, documentary, corporate, live, post and original-IP work to the same standard. Permits, crews, locations and finishing sit in one team, so international productions in Egypt do not have to assemble a vendor chain from scratch.": "من مقرنا في مدينة الإنتاج الإعلامي المصري، ومكاتبنا في دبي وجدة، ننفذ الأفلام والإعلانات والوثائقيات والمحتوى المؤسسي والبث المباشر وما بعد الإنتاج والملكية الفكرية الأصلية بمعيار واحد. التصاريح والطواقم والمواقع والتشطيب في فريق واحد، فلا تحتاج الإنتاجات الدولية في مصر إلى تجميع سلسلة مورّدين من الصفر.",
    "That is why clients return: one point of contact, a budget that holds, and a picture that still looks like the brief when it lands in every language and every cutdown.": "لهذا يعود العملاء: جهة اتصال واحدة، وميزانية تصمد، وصورة تبقى أمينة للبريف في كل لغة وكل نسخة.",
    "Three grounds. One standard.": "ثلاثة مقرات. معيار واحد.",
    "Led by Khaled Bendary — CEO": "بقيادة خالد بنداري — الرئيس التنفيذي",
    "Trusted by the titans": "يثق بنا العمالقة",
    "Team Member": "عضو الفريق",
    "Production": "الإنتاج",
    "Your next story starts here": "قصتك القادمة تبدأ من هنا",
    "Send us your objectives, scope and timeline. We'll return with the right production direction and next steps.": "أرسل لنا أهدافك ونطاق المشروع وجدوله الزمني، وسنعود إليك بالاتجاه الإنتاجي الصحيح والخطوات التالية.",
    "Your story is on its way": "قصتك في الطريق إليك",
    "We'll get back to you within one business day. If you need immediate assistance, write to us directly at": "سنعود إليك خلال يوم عمل واحد. وإذا احتجت مساعدة فورية، راسلنا مباشرة على",
    "Failed to submit form. Please try again, or use the button below to email us directly.": "فشل إرسال النموذج. حاول مرة أخرى، أو استخدم الزر أدناه لمراسلتنا مباشرة.",
    "Project not found": "المشروع غير موجود",
    "All work": "كل الأعمال",
    "Client": "العميل",
    "Category": "الفئة",
    "Metric": "النتيجة",
    "Duration": "المدة",
    "The brief & the build": "الفكرة والبناء",
    "Related productions": "إنتاجات ذات صلة",
    "Next project": "المشروع التالي",
    "Service not found": "الخدمة غير موجودة",
    "Service": "الخدمة",
    "Overview": "نظرة عامة",
    "Capabilities": "القدرات",
    "Full Description": "الوصف الكامل",
    "Related work": "أعمال ذات صلة",
    "Next service": "الخدمة التالية",
    "Article not found": "المقال غير موجود",
    "All insights": "كل المقالات",
    "Next article": "المقال التالي",
    "Written by Global Untold Story — Film Production Services, Egypt · UAE · KSA": "بقلم جلوبال أنتولد ستوري — خدمات إنتاج الأفلام، مصر · الإمارات · السعودية",
    "This story hasn't been shot yet": "هذه القصة لم تُصوَّر بعد",
    "Back home": "العودة للرئيسية",
    "Error 404": "خطأ 404",
    "Something went wrong": "حدث خطأ ما",
    "Try again": "حاول مرة أخرى",
    "The homepage didn't load. It's not you — try again.": "لم يتم تحميل الصفحة الرئيسية. ليست مشكلتك — حاول مرة أخرى.",
    "This page didn't load. It's not you — try again.": "لم يتم تحميل هذه الصفحة. ليست مشكلتك — حاول مرة أخرى.",
    "This project didn't load. It's not you — try again.": "لم يتم تحميل هذا المشروع. ليست مشكلتك — حاول مرة أخرى.",
    "This service didn't load. It's not you — try again.": "لم يتم تحميل هذه الخدمة. ليست مشكلتك — حاول مرة أخرى.",
    "This article didn't load. It's not you — try again.": "لم يتم تحميل هذا المقال. ليست مشكلتك — حاول مرة أخرى.",
  },
  de: {
    "Home": "Startseite",
    "Work": "Projekte",
    "Services": "Leistungen",
    "About": "Über uns",
    "Insights": "Einblicke",
    "Contact": "Kontakt",
    "Get a Quote": "Angebot anfordern",
    "Menu": "Menü",
    "Close": "Schließen",
    "Scroll": "Scrollen",
    "Start a project": "Projekt starten",
    "Offices": "Büros",
    "Back to top": "Nach oben",
    "Thirteen crafts. One cycle.": "Dreizehn Handwerke. Ein Zyklus.",
    "All services": "Alle Leistungen",
    "Our Work": "Unsere Arbeit",
    "Let's tell your untold story": "Lassen Sie uns Ihre unerzählte Geschichte erzählen",
    "Get in touch": "Kontakt aufnehmen",
    "Where story meets execution. Predictable budgets. Premium results.": "Wo Geschichte auf Ausführung trifft. Berechenbare Budgets. Erstklassige Ergebnisse.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Jede große Geschichte beginnt mit dem richtigen kreativen Partner, vereint durch einen Glauben. Jede Marke, jede Institution und jede Kultur hat eine Geschichte, die es wert ist, erzählt zu werden.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "Wir wählen unsere Kunden ebenso sorgfältig aus wie sie uns. Die stärkste Arbeit beginnt mit gemeinsamem Ehrgeiz, ehrlicher Zusammenarbeit und dem Vertrauen, sich gegenseitig herauszufordern, wenn die Geschichte es erfordert.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "Keine gewöhnlichen Dienstleister, die auf Anweisungen warten. Wir kommen als kreative Partner, bereit zu hinterfragen, beizutragen und Verantwortung zu übernehmen.",
    "Loading...": "Laden...",
    "Failed to load data": "Daten konnten nicht geladen werden",
    "Learn more →": "Mehr erfahren →",
    "Film & Video Production": "Film- und Videoproduktion",
  },
  es: {
    "Home": "Inicio",
    "Work": "Proyectos",
    "Services": "Servicios",
    "About": "Sobre nosotros",
    "Insights": "Artículos",
    "Contact": "Contacto",
    "Get a Quote": "Obtener cotización",
    "Menu": "Menú",
    "Close": "Cerrar",
    "Scroll": "Desplazar",
    "Start a project": "Iniciar un proyecto",
    "Offices": "Oficinas",
    "Back to top": "Volver arriba",
    "Thirteen crafts. One cycle.": "Trece oficios. Un ciclo.",
    "All services": "Todos los servicios",
    "Our Work": "Nuestro trabajo",
    "Let's tell your untold story": "Contemos tu historia no contada",
    "Get in touch": "Ponte en contacto",
    "Where story meets execution. Predictable budgets. Premium results.": "Donde la historia se une con la ejecución. Presupuestos previsibles. Resultados premium.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Toda gran historia comienza con el socio creativo adecuado, unidos por una sola creencia. Cada marca, cada institución y cada cultura tiene una historia que vale la pena contar.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "Elegimos a nuestros clientes tan cuidadosamente como ellos nos eligen a nosotros. El trabajo más fuerte comienza con una ambición compartida, una colaboración honesta y la confianza para desafiarse mutuamente cuando la historia lo requiere.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "No somos proveedores comunes esperando instrucciones. Llegamos como socios creativos preparados para cuestionar, contribuir y asumir la responsabilidad.",
    "Loading...": "Cargando...",
    "Failed to load data": "Error al cargar datos",
    "Learn more →": "Saber más →",
    "Film & Video Production": "Producción de Cine y Video",
  },
  fr: {
    "Home": "Accueil",
    "Work": "Projets",
    "Services": "Services",
    "About": "À propos",
    "Insights": "Insights",
    "Contact": "Contact",
    "Get a Quote": "Obtenir un devis",
    "Menu": "Menu",
    "Close": "Fermer",
    "Scroll": "Faire défiler",
    "Start a project": "Démarrer un projet",
    "Offices": "Bureaux",
    "Back to top": "Retour en haut",
    "Thirteen crafts. One cycle.": "Treize métiers. Un cycle.",
    "All services": "Tous les services",
    "Our Work": "Notre travail",
    "Let's tell your untold story": "Racontons votre histoire inédite",
    "Get in touch": "Prendre contact",
    "Where story meets execution. Predictable budgets. Premium results.": "Quand l'histoire rencontre la réalisation. Budgets prévisibles. Résultats premium.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Toute grande histoire commence avec le bon partenaire créatif, unis par une même conviction. Chaque marque, chaque institution et chaque culture a une histoire qui mérite d'être racontée.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "Nous choisissons nos clients aussi soigneusement qu'ils nous choisissent. Le travail le plus fort commence par une ambition partagée, une collaboration sincère et la confiance nécessaire pour se défier lorsque l'histoire l'exige.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "Pas de simples prestataires en attente d'instructions. Nous arrivons en tant que partenaires créatifs prêts à questionner, contribuer et s'investir pleinement.",
    "Loading...": "Chargement...",
    "Failed to load data": "Échec du chargement des données",
    "Learn more →": "En savoir plus →",
    "Film & Video Production": "Production de Films & Vidéos",
  },
  it: {
    "Home": "Home",
    "Work": "Lavori",
    "Services": "Servizi",
    "About": "Chi siamo",
    "Insights": "Approfondimenti",
    "Contact": "Contatti",
    "Get a Quote": "Richiedi un preventivo",
    "Menu": "Menu",
    "Close": "Chiudi",
    "Scroll": "Scorri",
    "Start a project": "Avvia un progetto",
    "Offices": "Uffici",
    "Back to top": "Torna in alto",
    "Thirteen crafts. One cycle.": "Tredici mestieri. Un ciclo.",
    "All services": "Tutti i servizi",
    "Our Work": "Il nostro lavoro",
    "Let's tell your untold story": "Raccontiamo la tua storia mai raccontata",
    "Get in touch": "Mettiti in contatto",
    "Where story meets execution. Predictable budgets. Premium results.": "Dove la storia incontra l'esecuzione. Budget prevedibili. Risultati premium.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Ogni grande storia inizia con il giusto partner creativo, uniti da un'unica convinzione. Ogni brand, ogni istituzione e ogni cultura ha una storia che vale la pena raccontare.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "Scegliamo i nostri clienti con la stessa cura con cui loro scelgono noi. Il lavoro più forte inizia con un'ambizione condivisa, una collaborazione onesta e la fiducia nel mettersi alla prova a vicenda quando la storia lo richiede.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "Non i soliti fornitori in attesa di istruzioni. Arriviamo come partner creativi pronti a mettere in discussione, contribuire e prendere l'iniziativa.",
    "Loading...": "Caricamento...",
    "Failed to load data": "Impossibile caricare i dati",
    "Learn more →": "Scopri di più →",
    "Film & Video Production": "Produzione Film e Video",
  },
  pt: {
    "Home": "Início",
    "Work": "Portfólio",
    "Services": "Serviços",
    "About": "Sobre",
    "Insights": "Insights",
    "Contact": "Contato",
    "Get a Quote": "Obter um orçamento",
    "Menu": "Menu",
    "Close": "Fechar",
    "Scroll": "Rolar",
    "Start a project": "Iniciar um projeto",
    "Offices": "Escritórios",
    "Back to top": "Voltar ao topo",
    "Thirteen crafts. One cycle.": "Treze ofícios. Um ciclo.",
    "All services": "Todos os serviços",
    "Our Work": "Nosso Trabalho",
    "Let's tell your untold story": "Vamos contar a sua história não contada",
    "Get in touch": "Entre em contato",
    "Where story meets execution. Predictable budgets. Premium results.": "Onde a história encontra a execução. Orçamentos previsíveis. Resultados premium.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Toda grande história começa com o parceiro criativo certo, unidos por uma única crença. Cada marca, cada instituição e cada cultura tem uma história que vale a pena ser contada.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "Escolhemos nossos clientes com o mesmo cuidado com que eles nos escolhem. O trabalho mais forte começa com ambição compartilhada, colaboração honesta e confiança para desafiar uns aos outros quando a história exige.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "Não somos fornecedores comuns esperando instruções. Chegamos como parceiros criativos preparados para questionar, contribuir e assumir a responsabilidade.",
    "Loading...": "Carregando...",
    "Failed to load data": "Falha ao carregar dados",
    "Learn more →": "Saiba mais →",
    "Film & Video Production": "Produção de Filme & Vídeo",
  },
  tr: {
    "Home": "Ana Sayfa",
    "Work": "Projeler",
    "Services": "Hizmetler",
    "About": "Hakkımızda",
    "Insights": "İçgörüler",
    "Contact": "İletişim",
    "Get a Quote": "Teklif Alın",
    "Menu": "Menü",
    "Close": "Kapat",
    "Scroll": "Aşağı Kaydır",
    "Start a project": "Proje Başlat",
    "Offices": "Ofisler",
    "Back to top": "Yukarı Dön",
    "Thirteen crafts. One cycle.": "On üç zanaat. Tek bir döngü.",
    "All services": "Tüm Hizmetler",
    "Our Work": "Çalışmalarımız",
    "Let's tell your untold story": "Anlatılmamış hikayenizi anlatalım",
    "Get in touch": "İletişime Geçin",
    "Where story meets execution. Predictable budgets. Premium results.": "Hikayenin icrayla buluştuğu yer. Öngörülebilir bütçeler. Üst düzey sonuçlar.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Her harika hikaye doğru kreatif ortakla başlar, tek bir inançla birleşir. Her markanın, her kurumun ve her kültürün anlatılmaya değer bir hikayesi vardır.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "Müşterilerimizi onların bizi seçtiği kadar özenle seçiyoruz. En güçlü işler, ortak hırs, dürüst iş birliği ve hikaye gerektirdiğinde birbirine meydan okuma güveniyle başlar.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "Talimat bekleyen sıradan tedarikçiler değiliz. Sorgulamaya, katkıda bulunmaya ve sahiplenmeye hazır kreatif ortaklar olarak geliyoruz.",
    "Loading...": "Yükleniyor...",
    "Failed to load data": "Veri yüklenemedi",
    "Learn more →": "Daha Fazla Bilgi →",
    "Film & Video Production": "Film ve Video Yapımı",
  },
  ru: {
    "Home": "Главная",
    "Work": "Работы",
    "Services": "Услуги",
    "About": "О нас",
    "Insights": "Блог",
    "Contact": "Контакты",
    "Get a Quote": "Получить смету",
    "Menu": "Меню",
    "Close": "Закрыть",
    "Scroll": "Листайте вниз",
    "Start a project": "Начать проект",
    "Offices": "Офисы",
    "Back to top": "Наверх",
    "Thirteen crafts. One cycle.": "Тринадцать ремесел. Один цикл.",
    "All services": "Все услуги",
    "Our Work": "Наши работы",
    "Let's tell your untold story": "Давайте расскажем вашу нерассказанную историю",
    "Get in touch": "Связаться",
    "Where story meets execution. Predictable budgets. Premium results.": "Там, где история встречается с исполнением. Предсказуемые бюджеты. Премиум-результаты.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Каждая великая история начинается с правильного творческого партнера, объединенного одной верой. У каждого бренда, каждого института и каждой культуры есть история, достойная того, чтобы ее рассказали.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "Мы выбираем наших клиентов так же тщательно, как и они нас. Самая сильная работа начинается с общих амбиций, честного сотрудничества и уверенности в том, чтобы бросать вызов друг другу, когда этого требует история.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "Не обычные подрядчики, ожидающие указаний. Мы приходим как творческие партнеры, готовые задавать вопросы, вносить свой вклад и брать на себя ответственность.",
    "Loading...": "Загрузка...",
    "Failed to load data": "Не удалось загрузить данные",
    "Learn more →": "Подробнее →",
    "Film & Video Production": "Кино- и видеопроизводство",
  },
  zh: {
    "Home": "首页",
    "Work": "案例作品",
    "Services": "核心服务",
    "About": "关于我们",
    "Insights": "最新动态",
    "Contact": "联系我们",
    "Get a Quote": "获取报价",
    "Menu": "菜单",
    "Close": "关闭",
    "Scroll": "向下滑动",
    "Start a project": "开启项目",
    "Offices": "办事处",
    "Back to top": "返回顶部",
    "Thirteen crafts. One cycle.": "十三种工艺。一个周期。",
    "All services": "全部服务",
    "Our Work": "我们的工作",
    "Let's tell your untold story": "让我们讲述您未说出口的故事",
    "Get in touch": "保持联系",
    "Where story meets execution. Predictable budgets. Premium results.": "故事与执行的完美契合。预算可控。成果非凡。",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "每一个伟大的故事都始于合适的创意合作伙伴，因同一个信念而凝聚。每个品牌、每个机构和一种文化都有一个值得讲述的故事。",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "我们如同客户选择我们一样仔细地选择他们。最出色的作品源于共同的雄心、坦诚的合作以及在剧情需要时互相挑战的信心。",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "我们不是等待指令的普通供应商。我们作为创意合作伙伴到来，准备提出疑问、做出贡献并承担责任。",
    "Loading...": "加载中...",
    "Failed to load data": "数据加载失败",
    "Learn more →": "了解更多 →",
    "Film & Video Production": "影视与视频制作",
  },
  en: {
    "Home": "Home",
    "Work": "Work",
    "Services": "Services",
    "About": "About",
    "Insights": "Insights",
    "Contact": "Contact",
    "Get a Quote": "Get a Quote",
    "Menu": "Menu",
    "Close": "Close",
    "Scroll": "Scroll",
    "Start a project": "Start a project",
    "Offices": "Offices",
    "Back to top": "Back to top",
    "Thirteen crafts. One cycle.": "Thirteen crafts. One cycle.",
    "All services": "All services",
    "Our Work": "Our Work",
    "Let's tell your untold story": "Let's tell your untold story",
    "Get in touch": "Get in touch",
    "Where story meets execution. Predictable budgets. Premium results.": "Where story meets execution. Predictable budgets. Premium results.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.",
    "Loading...": "Loading...",
    "Failed to load data": "Failed to load data",
    "Learn more →": "Learn more →",
    "Film & Video Production": "Film & Video Production",
  },
  ja: {
    "Home": "ホーム",
    "Work": "実績紹介",
    "Services": "サービス",
    "About": "私たちについて",
    "Insights": "インサイト",
    "Contact": "お問い合わせ",
    "Get a Quote": "見積もりを依頼",
    "Menu": "メニュー",
    "Close": "閉じる",
    "Scroll": "スクロール",
    "Start a project": "プロジェクトを始める",
    "Offices": "オフィス",
    "Back to top": "トップに戻る",
    "Thirteen crafts. One cycle.": "13の技術。1つのサイクル。",
    "All services": "すべてのサービス",
    "Our Work": "実績紹介",
    "Let's tell your untold story": "語られないストーリーを形にする",
    "Get in touch": "連絡する",
    "Where story meets execution. Predictable budgets. Premium results.": "ストーリーと実行が交わるところ。予測可能な予算。プレミアムな結果。",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "すべての素晴らしいストーリーは、1つの信念のもとに結ばれた適切なクリエイティブパートナーから始まります。あらゆるブランド、機関、文化には、語る価値のあるストーリーがあります。",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "お客様が私達を選ぶのと同様に、私達も慎重にお客様を選びます。最も力強い仕事は、共有された野心、誠実なコラボレーションから始まります。",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "指示を待つ普通のベンダーではありません。質問し、貢献し、責任を持つ準備ができたクリエイティブパートナーとして参加します。",
    "Loading...": "読み込み中...",
    "Failed to load data": "データの読み込みに失敗しました",
    "Learn more →": "詳細はこちら →",
    "Film & Video Production": "映画＆ビデオ制作",
  },
  ko: {
    "Home": "홈",
    "Work": "포트폴리오",
    "Services": "서비스",
    "About": "소개",
    "Insights": "인사이트",
    "Contact": "문의하기",
    "Get a Quote": "견적 요청",
    "Menu": "메뉴",
    "Close": "닫기",
    "Scroll": "스크롤",
    "Start a project": "프로젝트 시작",
    "Offices": "오피스",
    "Back to top": "맨 위로",
    "Thirteen crafts. One cycle.": "13가지 크래프트. 하나의 사이클.",
    "All services": "모든 서비스",
    "Our Work": "포트폴리오",
    "Let's tell your untold story": "당신의 숨겨진 이야기를 들려주세요",
    "Get in touch": "연락하기",
    "Where story meets execution. Predictable budgets. Premium results.": "이야기가 실행을 만나는 곳. 예측 가능한 예산. 프리미엄 결과.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "모든 위대한 이야기는 하나의 신념으로 뭉친 올바른 크리에이티브 파트너와 함께 시작됩니다. 모든 브랜드, 기관, 문화에는 들려줄 가치가 있는 이야기가 있습니다.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "고객이 저희를 선택하는 것처럼 저희도 고객을 신중하게 선택합니다. 가장 강력한 작업은 공유된 야망, 정직한 협업, 그리고 서로에게 도전할 수 있는 자신감에서 시작됩니다.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "지시를 기다리는 일반적인 공급업체가 아닙니다. 저희는 질문하고, 기여하며, 주도권을 가질 준비가 된 크리에이티브 파트너로 함께합니다.",
    "Loading...": "로딩 중...",
    "Failed to load data": "데이터 로드 실패",
    "Learn more →": "자세히 보기 →",
    "Film & Video Production": "영화 및 비디오 제작",
  },
  pl: {
    "Home": "Start",
    "Work": "Projekty",
    "Services": "Usługi",
    "About": "O nas",
    "Insights": "Artykuły",
    "Contact": "Kontakt",
    "Get a Quote": "Uzyskaj wycenę",
    "Menu": "Menu",
    "Close": "Zamknij",
    "Scroll": "Przewiń",
    "Start a project": "Rozpocznij projekt",
    "Offices": "Biura",
    "Back to top": "Powrót na górę",
    "Thirteen crafts. One cycle.": "Trzynaście rzemiosł. Jeden cykl.",
    "All services": "Wszystkie usługi",
    "Our Work": "Nasze prace",
    "Let's tell your untold story": "Opowiedzmy Twoją nieopowiedzianą historię",
    "Get in touch": "Skontaktuj się",
    "Where story meets execution. Predictable budgets. Premium results.": "Gdzie historia spotyka się z realizacją. Przewidywalne budżety. Najwyższa jakość.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Każda wielka historia zaczyna się od właściwego partnera kreatywnego, połączonego jedną wiarą. Każda marka, każda instytucja i każda kultura ma historię wartą opowiedzenia.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "Wybieramy naszych klientów równie starannie, jak oni wybierają nas. Najsilniejsza praca zaczyna się od wspólnych ambicji, uczciwej współpracy i pewności siebie, by rzucać sobie wyzwania, gdy wymaga tego historia.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "Nie jesteśmy zwykłymi dostawcami czekającymi na instrukcje. Przybywamy jako partnerzy kreatywni gotowi zadawać pytania, wnosić wkład i brać odpowiedzialność.",
    "Loading...": "Ładowanie...",
    "Failed to load data": "Nie udało się załadować danych",
    "Learn more →": "Dowiedz się więcej →",
    "Film & Video Production": "Produkcja filmowa i wideo",
  },
  sw: {
    "Home": "Nyumbani",
    "Work": "Kazi Zetu",
    "Services": "Huduma",
    "About": "Kuhusu Sisi",
    "Insights": "Makala",
    "Contact": "Wasiliana",
    "Get a Quote": "Pata Nukuu",
    "Menu": "Menyu",
    "Close": "Funga",
    "Scroll": "Teleza",
    "Start a project": "Anza mradi",
    "Offices": "Ofisi",
    "Back to top": "Rudi juu",
    "Thirteen crafts. One cycle.": "Ufundi kumi na tatu. Mzunguko mmoja.",
    "All services": "Huduma zote",
    "Our Work": "Kazi Zetu",
    "Let's tell your untold story": "Hebu tusimulie hadithi yako ambayo haijasimuliwa",
    "Get in touch": "Wasiliana nasi",
    "Where story meets execution. Predictable budgets. Premium results.": "Ambapo hadithi hukutana na utekelezaji. Bajeti zinazotabirika. Matokeo ya premium.",
    "Every great story begins with the right creative partner, united by one belief. Every brand, every institution and every culture has a story worth telling.": "Kila hadithi kuu huanza na mshirika sahihi wa ubunifu, aliyeunganishwa na imani moja. Kila chapa, kila taasisi na kila utamaduni una hadithi inayostahili kusimuliwa.",
    "We choose our clients as carefully as they choose us. The strongest work begins with shared ambition, honest collaboration and the confidence to challenge one another when the story demands it.": "Tunawachagua wateja wetu kwa umakini kama wanavyotuchagua sisi. Kazi yenye nguvu zaidi huanza na nia ya pamoja, ushirikiano wa uaminifu na kujiamini katika changamoto wakati hadithi inapohitaji.",
    "Not your regular vendors waiting for instructions. We arrive as creative partners prepared to question, contribute and take ownership.": "Sio wauzaji wako wa kawaida wanaosubiri maagizo. Tunakuja kama washirika wa ubunifu waliojitayarisha kuhoji, kuchangia na kuchukua umiliki.",
    "Loading...": "Inapakia...",
    "Failed to load data": "Imeshindwa kupakia data",
    "Learn more →": "Jifunze zaidi →",
    "Film & Video Production": "Uzalishaji wa Filamu na Video",
  }
};

interface LanguageContextProps {
  locale: string;
  dir: 'ltr' | 'rtl';
  changeLocale: (code: string) => void;
  /** Where this same page lives in another language. */
  localeHref: (code: string) => string;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const pathname = usePathname() || '/';
  const router = useRouter();

  // The URL is the single source of truth. Reading it here (instead of
  // localStorage) means the server and the client agree on the language, so
  // the rendered HTML is the language the URL promises — which is what makes
  // the translated pages indexable at all.
  const { locale, bare } = useMemo(() => {
    const [, first, ...rest] = pathname.split('/');
    /*
     * Strip the prefix for English too. English is served unprefixed, but the
     * app route is [locale], so at prerender the pathname is "/en/services"
     * while in the browser it is "/services". Excluding the default locale
     * here left `bare` as "/en/services" during the build, and the language
     * links came out as "/ar/en/services". The locale is the same either way;
     * only `bare` was wrong, and only in the HTML the crawler reads.
     */
    if (isLocale(first)) {
      return { locale: first, bare: `/${rest.join('/')}`.replace(/\/$/, '') || '/' };
    }
    return { locale: DEFAULT_LOCALE, bare: pathname };
  }, [pathname]);

  /*
   * The switcher needs a real URL, not just a handler. It was a row of
   * <button onClick>, so the rendered HTML contained no link to any other
   * language: readers without JavaScript had no way across, and crawlers had
   * only the hreflang tags and the sitemaps to go on. Those do the job, but a
   * link is what the page should have been offering all along.
   */
  const localeHref = (code: string) => localizedPath(bare, code);

  const changeLocale = (code: string) => {
    if (!isLocale(code) || code === locale) return;
    router.push(localizedPath(bare, code));
  };

  const t = (key: string) => translations[locale]?.[key] || translations['en']?.[key] || key;

  return (
    <LanguageContext.Provider value={{ locale, dir: localeDir(locale), changeLocale, localeHref, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function useTranslation() {
  const { locale, t } = useLanguage();
  return { t, locale };
}
